### ISSUE TITLE
Parametrise number of events in sdk

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dhis2-android-sdk#13]
Parametrise how many events are downloaded. At the moment 200 events are downloaded (hardcoded number). This should be the value by default.

**Comment by ivanarrizabalaga** [comment]
add this from import_summary_222

**Comment by ivanarrizabalaga** [comment]
Turned into an static member in **TrackerDataLoader** that can be changes via:

```
TrackerDataLoader.setMaxEvents(50)
```
