### ISSUE TITLE
Retrieve all OrgUnits parameters

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#19]
The SDK is currently downloading just a few parameters for each OrgUnit. We need to add columns in the SDK DB to hold all the OrtUnit parameters that we've actually available in the json answer to the API call

**Comment by idelcano** [comment]
@ifoche i have only one question:
The organisationUnits have some elements like:
<users>
<userItem id="n6cLjx1VJfw"/>
<userItem id="c5GqNvfuus2"/>
</users>

<organisationUnitGroups>
<organisationUnitGroup id="xdnfH7jiCUp"/>
<organisationUnitGroup id="NAHlpJzIfbi"/>
</organisationUnitGroups>

The same with ancestors, childrens, dataSets and programs.

should I create organisationUnitUserItem, organisationUnitGroup, organisationUnitAncestor, organisationUnitChildren, organisationUnitDataSet and organisationUnitProgram tables?

Or some table is not needed?


Example in:
https://hnqis-dev-staging.psi-mis.org/api/organisationUnits/QS7sK8XzdQc?fields=[%3Aall]
thanks!

**Comment by ifoche** [comment]
Hi @idelcano, I would say that userItem is pointing to a user, isn't it? in that case, there wouldn't be an organisationUnitUserItem, but a link between organisationUnit and User...don't you think? (so a new "List<User> assignedUsers" field in OrganisationUnit pojo I would say)
With ancestors and children, that information is in reality the info that @ivanarrizabalaga is going to use to build the orgUnit tree in the visitors side, so I would say maybe it is better if you don't touch it, so @ivanarrizabalaga can add it himself.
For the DataSet, yes, I imagine that probably you would have to create a new pojo, but in the case of the Program, I think that a reference to the Program would be enough (as with the users).

Do you agree?
