### ISSUE TITLE
Implement missing program rule functions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#255]
Please 
- use TDD for the implementation. 
- take note of the implementation made in trackercapture from @tokland, concretely in [this PR](https://github.com/EyeSeeTea/dhis2-android-sdk/pull/251)

**Comment by idelcano** [comment]
@ifoche i found two functions not implemented in tracker capture:
checkControlDigits: not implemented in the web app 
https://github.com/dhis2/d2-tracker/blob/master/src/dhis2.angular.services.js#L2380

addControlDigits: implemented in trackercapture web app but not in android app 
https://github.com/dhis2/d2-tracker/blob/master/src/dhis2.angular.services.js#L2323

should i add them?

**Comment by tokland** [comment]
@idelcano We decided with @ifoche to implement only functions available in Maintenance->ProgramRule interface (i.e. https://play.dhis2.org/demo/dhis-web-maintenance/#/edit/programSection/programRule/IdrDtQmRGrv), but that was mainly because we were short of time, let's see now.

**Comment by idelcano** [comment]
@xurxodev you can ignore these comments.   i created a new [issue](https://github.com/EyeSeeTea/dhis2-android-sdk/issues/267) to implement it
