### ISSUE TITLE
Download category, category options & category combinations metadata

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#274]

**Comment by Amejia481** [comment]
I have some difficulties merging the pull request #273 with mine.

The way that migrations test are done is causing issues with the actual version of the DB.

 I was talking with @idelcano about the situation, but it's pending to find a new approach to tackle the difficulty.

Meanwhile, could I skip the merge and make pull request again the development branch?
@ifoche  @xurxodev
