### ISSUE TITLE
Observe changes on server for User with Rabbitmq

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/dhis2-android-sdk#319]
- [ ] update MetadataAuditConsumerMockIntegrationShould
- [ ] create test for create
- [ ] create test for update
- [ ] create test for delete
- [ ] update MetadataAuditHandlerFactoryShould

**Comment by idelcano** [comment]
User is not listed in the maintenance  webapp and is not supported by rabbitmq at this momment.
