### ISSUE TITLE
Download Option Attributes in the sdk

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#35]

**Comment by ivanarrizabalaga** [comment]
@josemp10 , I'm trying to add the pull of option attributes from the server and I'm facing to problems:

 1) Is it possible to view the option attributes from the server interface? I cant find the option and it would be great to check what I'm doing.

2) I'm not able to retrieve option attributeValues using the filters of the api, any clue?

More info about the api (http://dhis2.github.io/dhis2-docs/master/en/developer/html/dhis2_developer_manual_full.html#d4969e239):


**List all attributes**:
	https://hnqis-dev-ci.psi-mis.org/api/attributes

**Our factor attribute** (just to check that it exists):
	https://hnqis-dev-ci.psi-mis.org/api/attributes/DVzuBdj9kli

**Current sdk call to get optionset and options details**:
	https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*]	

```xml
		<metadata xmlns="http://dhis2.org/schema/dxf/2.0">
		    <optionSets>
		        <optionSet created="2016-02-08T12:55:09.940+0000" lastUpdated="2016-02-09T14:29:43.342+0000" name="DB - DE Type" id="akyRgB3QVhB">
		            <displayName>DB - DE Type</displayName>
		            ...
		            <options>
		                <option code="92" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.842+0000" name="QUESTION" id="OUuryREhgMK">
		                    <displayName>QUESTION</displayName>
		                    <externalAccess>false</externalAccess>
		                    <userGroupAccesses/>
		                    <attributeValues/>
		                </option>
		                <option code="93" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.096+0000" name="COMPOSITE_SCORE" id="mznbSsWOOpk">
		                    <displayName>COMPOSITE_SCORE</displayName>
		                    <externalAccess>false</externalAccess>
		                    <userGroupAccesses/>
		                    <attributeValues/>
		                </option>
```

**Checking path to attributeValues is the right one by filtering that field out (it works)**:
	https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,!attributeValues]

	You get the same xml without the attributeValues entry.

**Asking all from attributeValues	in different manners**:

https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,attributeValues[*]]

https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,attributeValues[*,attribute[*]]]

https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,attributeValues[*,attribute[name,displayName,created,lastUpdated,access,id,valueType,code]]]

https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,option[*,attributeValues[*]]]

None of these attempts return the info of the attributeValues, any clue?
PD: I' gonna create an issue to dhis to ask about this

**Comment by ivanarrizabalaga** [comment]
Just created an issue in their repo:

https://github.com/dhis2/dhis2-android-sdk/issues/60

**Comment by josemp10** [comment]
Hi!

So, it shoud be working now.

you should be able to see the optionattibutes using the web interface here
-> Apps -> DataAdministration-> OptionSets -> you select one optionset,
(Yes1No0), and when you edit the options you have to see the new
optionfactor attribute...

Using the web API call
https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options%5B*%5D
should give you now the attribute values:

Hope it is ok!

<optionSet code="Yes1No0" created="2015-10-15T18:25:40.361+0000" lastUpdated
="2015-10-15T18:27:04.069+0000" name="Yes1No0" id="cN5N9aj3S30">
<displayName>Yes1No0</displayName>
<publicAccess>rw------</publicAccess>
<version>1</version>
<externalAccess>false</externalAccess>
<valueType>TEXT</valueType>
<user id="NjbJCa6JkQu"/>
<userGroupAccesses/>
<attributeValues/>
<options>
<option code="Yes [1]" created="2015-11-04T21:36:53.000+0000" lastUpdated="
2016-02-22T18:23:27.958+0000" name="Yes" id="kkOywHQwQWE">
<displayName>Yes</displayName>
<externalAccess>false</externalAccess>
<userGroupAccesses/>
<attributeValues>
<attributeValue lastUpdated="2016-02-22T18:23:27.945+0000" created="
2016-02-22T18:23:27.940+0000">
<value>1</value>
<attribute id="DVzuBdj9kli"/>
</attributeValue>
</attributeValues>
</option>
<option code="No [0]" created="2015-11-04T21:36:53.000+0000" lastUpdated="
2016-02-22T18:23:34.602+0000" name="No" id="yVUHqeMvBJZ">
<displayName>No</displayName>
<externalAccess>false</externalAccess>
<userGroupAccesses/>
<attributeValues>
<attributeValue lastUpdated="2016-02-22T18:23:34.596+0000" created="
2016-02-22T18:23:34.596+0000">
<value>0</value>
<attribute id="DVzuBdj9kli"/>
</attributeValue>
</attributeValues>
</option>
</options>
</optionSet>

**Comment by ivanarrizabalaga** [comment]
@ifoche  , @idelcano just pushed my branch (https://github.com/EyeSeeTea/dhis2-android-sdk/tree/option_attributes) with the work in progress.

You need to complete the deserialization process to parse the attributes. The important code is:

**MetaDataController.getOptionSetDataFromServer**
**OptionSetWrapper.getOperations**

Notice that this process has already been done (or something similar) for ProgramAttributeValues and OrganisationUnitAttributeValue
