### ISSUE TITLE
Introduce patch method in sdk to submit just part of a survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#39]

**Comment by idelcano** [comment]
In my first steps, i created the follow methods in dhisapi class without exit.
I import the @patch from the sdk, and i look the "putEvent" and "postEvent" method to do this:

    @PATCH("/"+ApiEndpointContainer.EVENTS+"/")
    Response patchEvent(@Body Event event);
	
    @PATCH("/"+ApiEndpointContainer.EVENTS+"/{eventUid}")
    Response patchEvent(@Path("eventUid") String eventUid, @Body Event event);
	
Response:
 HTTP 200 https://hnqis-dev-ci.psi-mis.org/api/events/ (1417ms)
D/TrackerDataSender: {"httpStatus":"OK","httpStatusCode":200,"status":"OK","message":"Import was successful.","response":{"responseType":"ImportSummaries","imported":46,"updated":0,"deleted":0,"ignored":0,"importSummaries":[{"responseType":"ImportSummary","status":"SUCCESS","importCount":{"imported":46,"updated":0,"ignored":0,"deleted":0},"reference":"NflWMdSqm1S","href":"https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S"}]}}
D/Retrofit: ---> HTTP GET https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S?fields=created%2ClastUpdated
D/RepoManager: Request{method=GET, url=https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S?fields=created%2ClastUpdated, tag=Request{method=GET, url=https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S?fields=created%2ClastUpdated, tag=null}}
D/Retrofit: <--- HTTP 200 https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S?fields=created%2ClastUpdated (308ms)
D/Retrofit: ---> HTTP PATCH https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S
D/RepoManager: Request{method=PATCH, url=https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S, tag=Request{method=PATCH, url=https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S, tag=null}}
D/Retrofit: <--- HTTP 405 https://hnqis-dev-ci.psi-mis.org/api/events/NflWMdSqm1S (290ms)
D/RepoManager: there was an error..HTTP

Error in html format:


 <h1>HTTP Status 405 - Request method 'PATCH' not supported</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Request method 'PATCH' not supported</u></p><p><b>description</b> <u>The specified HTTP method is not allowed for the requested resource.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.54</h3></body>


Log:
D/trackerdatasender: Already create: Event{event='K1ciYl3coRc', status='COMPLETED', latitude=null, longitude=null, trackedEntityInstance='null', localEnrollmentId=0, enrollment='null', programId='Iq1D7YfHYA4', programStageId='upYw0TJU0zt', organisationUnitId='QS7sK8XzdQc', eventDate='2016-01-19T00:00:00.000+0000', dueDate='2016-03-26T01:51:20.448+0000', dataValues=null}
D/trackerdatasender: Already create: PATCH ITEvent{event='K1ciYl3coRc', status='COMPLETED', latitude=null, longitude=null, trackedEntityInstance='null', localEnrollmentId=0, enrollment='null', programId='Iq1D7YfHYA4', programStageId='upYw0TJU0zt', organisationUnitId='QS7sK8XzdQc', eventDate='2016-01-19T00:00:00.000+0000', dueDate='2016-03-26T01:51:20.448+0000', dataValues=null}
D/Retrofit: ---> HTTP PATCH https://hnqis-dev-ci.psi-mis.org/api/events/K1ciYl3coRc
D/RepoManager: Request{method=PATCH, url=https://hnqis-dev-ci.psi-mis.org/api/events/K1ciYl3coRc, tag=Request{method=PATCH, url=https://hnqis-dev-ci.psi-mis.org/api/events/K1ciYl3coRc, tag=null}}
D/Retrofit: <--- HTTP 405 https://hnqis-dev-ci.psi-mis.org/api/events/K1ciYl3coRc (761ms)
D/RepoManager: there was an error..HTTP

Error in html format:
<h1>HTTP Status 405 - Request method 'PATCH' not supported</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Request method 'PATCH' not supported</u></p><p><b>description</b> <u>The specified HTTP method is not allowed for the requested resource.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.54</h3>

**Comment by ifoche** [comment]
Mmmmm, sounds like what client told us about patch being supported is not true (or not in this version), and we will have to use a workaround by downloading the existing data of a given survey and just using put (pre-filling the already filled in answers). However, we will talk about it on Monday if you want.
