### ISSUE TITLE
Test new 2.25 method to download events

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-sdk#83]
Try new method to download events proposed by @xurxodev

**Comment by ifoche** [comment]
can anyone tell me if this task is done? (I suppose yes, but it's in "To test" column without an associated PR (@idelcano? @xurxodev?)

**Comment by xurxodev** [comment]
I think yes is done because was the first task with sdk, It might not be well linked to the pull request
@ifoche @idelcano

**Comment by idelcano** [comment]
@ifoche  yes, it is finished.
This task don't have associated PR. It could be linked with: https://github.com/EyeSeeTea/malariapp/pull/1240
